### ISSUE TITLE
Conceal is lost on scroll

### ISSUE THREAD

**Issue by johngeorgewright** [tfausak/atom-conceal#6]
If you were to scroll past a concealed element, or use page up/down, all the concealed items are lost.

![conceal-issue](https://cloud.githubusercontent.com/assets/1423566/14209920/7c954c80-f81e-11e5-9b18-49a11397763d.gif)

**Comment by tfausak** [comment]
Yeah, I noticed this too. I'm not sure why it happens or how to fix it. It's best to think of this package as more of a proof of concept than a real product :)

**Comment by johngeorgewright** [comment]
Oaky doak. When I get time, I might look in to it too... it's been a while since I've looked that much in to atom's API. It seems to have changed some what.

**Comment by tfausak** [comment]
Alright. If you're interested in maintained or improving this project, I can add you as a contributor.

**Comment by tfausak** [comment]
I recognize that this is still a problem, but I'm not going to fix this.

**Comment by dpavlic** [comment]
Still interested in perhaps passing the torch on this or collaborating to make it a more robust package?

Fira Code Ligatures don't work for my purposes as far as I can see, which is to mask lambda calls in Python as λ; lambda is everywhere in the scientific computing stack, and reading lambda...lambda...lambda line in and line out is seriously exhausting. 

This is a very clean and minimalistic implementation of what I'm looking for. This is also the furthest anyone has gotten with this issue in Atom, AFAIK. 

As far as I can see, the scrolling issue is a result of using onDidStopChanging, which will update the visible elements once the buffer stops changing. Scrolling, say, to the top and back to the bottom doesn't actually trigger onDidStopChanging since there's no buffer change in that action; thus you lose the concealed replacements but there's no trigger to conceal back.

As a test: scroll all the way up, scroll back down. Concealed items gone. Add a line, or do whatever else which causes a change to the buffer (and stop for 300 ms to trigger onDidStopChanging) and everything is concealed again. I can't find scroll tracking on Atom's API, but there has to be a relatively clean way. onDidChangeCursorPosition is possible, but would cause a serious performance hit and doesn't directly fix the issue when scrolling (everything changes back only after the cursor is moved, not directly when scrolling). 

I don't have time to work on this in month, but would love to come back to it. Otherwise, I'll be forking away. Either way, thanks for this, it helps restore my sanity.

**Comment by tfausak** [comment]
> Still interested in perhaps passing the torch on this or collaborating to make it a more robust package?

Absolutely! If you can get things sorted out in a fork, I can add you as a maintainer to this repository. No rush, obviously :)
